facebook:
  app_id: 531977467377977
lang: en-us
optional_front_matter:
  remove_originals: true
readme_index:
  remove_originals: true
show_downloads: false
theme: jekyll-theme-primer
titles_from_headings:
  strip_title: true
twitter:
  card: summary
  username: jkmartindale